<?php

use App\Http\Controllers\Api\AttendanceController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\ChallanController;
use App\Http\Controllers\Api\ComplaintController;
use App\Http\Controllers\Api\DailyProgressReportController;
use App\Http\Controllers\Api\LabourAttendanceController;
use App\Http\Controllers\Api\MissedAttendanceRequestController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Middleware\AuthenticateApiToken;
use App\Http\Middleware\EnsureCompanySubscriptionActive;
use Illuminate\Support\Facades\Route;

Route::post('/login', [AuthController::class, 'login']);

Route::middleware([AuthenticateApiToken::class, EnsureCompanySubscriptionActive::class])->group(function () {
    Route::get('/user', [AuthController::class, 'profile'])->name('user');
    Route::get('/profile', [AuthController::class, 'profile']);
    Route::get('/attendance/me', [AttendanceController::class, 'me']);
    Route::get('/attendance/login-reminder', [AttendanceController::class, 'loginReminder'])->name('api.attendance.login-reminder');
    Route::get('/attendance/daily-report', [AttendanceController::class, 'dailyReport']);
    Route::post('/attendance/leave', [AttendanceController::class, 'applyLeave']);
    Route::post('/attendance/clock-in', [AttendanceController::class, 'clockIn']);
    Route::post('/attendance/clock-out', [AttendanceController::class, 'clockOut']);
    Route::get('/attendance/missed-requests', [MissedAttendanceRequestController::class, 'index'])->name('api.attendance.missed-requests.index');
    Route::post('/attendance/missed-requests', [MissedAttendanceRequestController::class, 'store'])->name('api.attendance.missed-requests.store');
    Route::get('/attendance/missed-requests/{missedAttendanceRequest}', [MissedAttendanceRequestController::class, 'show'])->name('api.attendance.missed-requests.show');
    Route::get('/missed-requests', [MissedAttendanceRequestController::class, 'index'])->name('api.missed-requests.index');
    Route::post('/missed-requests', [MissedAttendanceRequestController::class, 'store'])->name('api.missed-requests.store');
    Route::get('/missed-requests/{missedAttendanceRequest}', [MissedAttendanceRequestController::class, 'show'])->name('api.missed-requests.show');
    Route::get('/complaints', [ComplaintController::class, 'index'])->name('api.complaints.index');
    Route::post('/complaints', [ComplaintController::class, 'store'])->name('api.complaints.store');
    Route::get('/complaints/{complaint}', [ComplaintController::class, 'show'])->name('api.complaints.show');
    Route::get('/complaint', [ComplaintController::class, 'index'])->name('api.complaint.index');
    Route::post('/complaint', [ComplaintController::class, 'store'])->name('api.complaint.store');
    Route::get('/complaint/{complaint}', [ComplaintController::class, 'show'])->name('api.complaint.show');
    Route::get('/challans', [ChallanController::class, 'index'])->name('api.challans.index');
    Route::post('/challans', [ChallanController::class, 'store'])->name('api.challans.store');
    Route::get('/challans/{challan}', [ChallanController::class, 'show'])->name('api.challans.show');
    Route::get('/challans/{challan}/pdf', [ChallanController::class, 'pdf'])->name('api.challans.pdf');
    Route::get('/challans/{challan}/pdf-data', [ChallanController::class, 'pdfData'])->name('api.challans.pdf-data');
    Route::get('/challan', [ChallanController::class, 'index'])->name('api.challan.index');
    Route::post('/challan', [ChallanController::class, 'store'])->name('api.challan.store');
    Route::get('/challan/{challan}', [ChallanController::class, 'show'])->name('api.challan.show');
    Route::get('/dprs', [DailyProgressReportController::class, 'index'])->name('api.dprs.index');
    Route::post('/dprs', [DailyProgressReportController::class, 'store'])->name('api.dprs.store');
    Route::get('/dprs/{dailyProgressReport}', [DailyProgressReportController::class, 'show'])->name('api.dprs.show');
    Route::get('/dpr', [DailyProgressReportController::class, 'index'])->name('api.dpr.index');
    Route::post('/dpr', [DailyProgressReportController::class, 'store'])->name('api.dpr.store');
    Route::get('/dpr/{dailyProgressReport}', [DailyProgressReportController::class, 'show'])->name('api.dpr.show');
    Route::get('/dpr-photos/{photo}', [DailyProgressReportController::class, 'photo'])->name('api.dpr-photos.show');
    Route::get('/labour/sites', [LabourAttendanceController::class, 'sites'])->name('api.labour.sites');
    Route::get('/labour/sites/{labourSite}/contractors', [LabourAttendanceController::class, 'contractors'])->name('api.labour.contractors');
    Route::get('/labour/contractors/{contractor}/labours', [LabourAttendanceController::class, 'labours'])->name('api.labour.labours');
    Route::get('/labour/attendances', [LabourAttendanceController::class, 'index'])->name('api.labour-attendances.index');
    Route::post('/labour/attendances', [LabourAttendanceController::class, 'store'])->name('api.labour-attendances.store');
    Route::get('/labour/attendances/{labourAttendance}/photo', [LabourAttendanceController::class, 'photo'])->name('api.labour-attendances.photo');
    Route::get('/labour/attendances/{labourAttendance}', [LabourAttendanceController::class, 'show'])->name('api.labour-attendances.show');
    Route::get('/labor/sites', [LabourAttendanceController::class, 'sites'])->name('api.labor.sites');
    Route::get('/labor/sites/{labourSite}/contractors', [LabourAttendanceController::class, 'contractors'])->name('api.labor.contractors');
    Route::get('/labor/contractors/{contractor}/labors', [LabourAttendanceController::class, 'labours'])->name('api.labor.labors');
    Route::get('/labor/attendances', [LabourAttendanceController::class, 'index'])->name('api.labor-attendances.index');
    Route::post('/labor/attendances', [LabourAttendanceController::class, 'store'])->name('api.labor-attendances.store');
    Route::get('/labor/attendances/{labourAttendance}/photo', [LabourAttendanceController::class, 'photo'])->name('api.labor-attendances.photo');
    Route::get('/labor/attendances/{labourAttendance}', [LabourAttendanceController::class, 'show'])->name('api.labor-attendances.show');
    Route::post('/payments', [PaymentController::class, 'store'])->name('api.payments.store');
    Route::get('/payments', [PaymentController::class, 'index'])->name('api.payments.index');
    Route::get('/payments/{payment}', [PaymentController::class, 'show'])->name('api.payments.show');
    Route::get('/payments/{payment}/slip', [PaymentController::class, 'slip'])->name('api.payments.slip');
    Route::get('/payments/{payment}/slip-data', [PaymentController::class, 'slipData'])->name('api.payments.slip-data');
});
