<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\AttendanceReportController;
use App\Http\Controllers\Admin\ChallanController;
use App\Http\Controllers\Admin\CompanyController;
use App\Http\Controllers\Admin\ComplaintController;
use App\Http\Controllers\Admin\DailyProgressReportController;
use App\Http\Controllers\Admin\DailyDieselPurchaseController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\EmployeeController;
use App\Http\Controllers\Admin\FddTestRecordController;
use App\Http\Controllers\Admin\LabourAttendanceController;
use App\Http\Controllers\Admin\LeaveRequestController;
use App\Http\Controllers\Admin\MachineryDieselLogController;
use App\Http\Controllers\Admin\MaterialStockController;
use App\Http\Controllers\Admin\MissedAttendanceRequestController;
use App\Http\Controllers\Admin\MirFileReportController;
use App\Http\Controllers\Admin\PaymentController;
use App\Http\Controllers\Admin\ProductPurchaseController;
use App\Http\Controllers\Admin\VehicleController;
use App\Http\Controllers\Admin\VehicleDriverAttendanceController;
use App\Http\Controllers\Admin\VehicleLogController;
use App\Http\Middleware\EnsureAdminLoggedIn;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('login.store');

    Route::middleware(EnsureAdminLoggedIn::class)->group(function () {
        Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
        Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
        Route::get('/companies', [CompanyController::class, 'index'])->name('companies.index');
        Route::get('/companies/create', [CompanyController::class, 'create'])->name('companies.create');
        Route::post('/companies', [CompanyController::class, 'store'])->name('companies.store');
        Route::get('/companies/{company}', [CompanyController::class, 'show'])->name('companies.show');
        Route::post('/companies/{company}/database', [CompanyController::class, 'provisionDatabase'])->name('companies.database');
        Route::post('/companies/{company}/renew', [CompanyController::class, 'renew'])->name('companies.renew');
        Route::patch('/companies/{company}/status', [CompanyController::class, 'updateStatus'])->name('companies.status');
        Route::patch('/companies/{company}/users/{user}/permissions', [CompanyController::class, 'updateUserPermissions'])->name('companies.users.permissions');
        Route::get('/today-attendance', [AttendanceReportController::class, 'today'])->name('today-attendance.index');
        Route::get('/attendance-reports', [AttendanceReportController::class, 'index'])->name('attendance-reports.index');
        Route::get('/attendance-reports/export', [AttendanceReportController::class, 'export'])->name('attendance-reports.export');
        Route::get('/dpr-reports', [DailyProgressReportController::class, 'index'])->name('dpr-reports.index');
        Route::get('/dpr-reports/photos/{photo}', [DailyProgressReportController::class, 'photo'])->name('dpr-reports.photo');
        Route::get('/dpr-reports/{dailyProgressReport}', [DailyProgressReportController::class, 'show'])->name('dpr-reports.show');
        Route::get('/fdd-test-records', [FddTestRecordController::class, 'index'])->name('fdd-test-records.index');
        Route::post('/fdd-test-records', [FddTestRecordController::class, 'store'])->name('fdd-test-records.store');
        Route::post('/fdd-road-sections', [FddTestRecordController::class, 'storeRoadSection'])->name('fdd-road-sections.store');
        Route::get('/fdd-test-records/export', [FddTestRecordController::class, 'export'])->name('fdd-test-records.export');
        Route::get('/fdd-test-records/{fddTestRecord}/edit', [FddTestRecordController::class, 'edit'])->name('fdd-test-records.edit');
        Route::put('/fdd-test-records/{fddTestRecord}', [FddTestRecordController::class, 'update'])->name('fdd-test-records.update');
        Route::delete('/fdd-test-records/{fddTestRecord}', [FddTestRecordController::class, 'destroy'])->name('fdd-test-records.destroy');
        Route::get('/mir-file-reports', [MirFileReportController::class, 'index'])->name('mir-file-reports.index');
        Route::post('/mir-file-reports', [MirFileReportController::class, 'store'])->name('mir-file-reports.store');
        Route::get('/mir-file-reports/export', [MirFileReportController::class, 'export'])->name('mir-file-reports.export');
        Route::get('/mir-file-reports/{mirFileReport}/edit', [MirFileReportController::class, 'edit'])->name('mir-file-reports.edit');
        Route::put('/mir-file-reports/{mirFileReport}', [MirFileReportController::class, 'update'])->name('mir-file-reports.update');
        Route::delete('/mir-file-reports/{mirFileReport}', [MirFileReportController::class, 'destroy'])->name('mir-file-reports.destroy');
        Route::get('/challans', [ChallanController::class, 'index'])->name('challans.index');
        Route::get('/challans/export', [ChallanController::class, 'export'])->name('challans.export');
        Route::get('/challans/{challan}/download', [ChallanController::class, 'download'])->name('challans.download');
        Route::get('/complaints', [ComplaintController::class, 'index'])->name('complaints.index');
        Route::patch('/complaints/{complaint}', [ComplaintController::class, 'update'])->name('complaints.update');
        Route::get('/missed-requests', [MissedAttendanceRequestController::class, 'index'])->name('missed-requests.index');
        Route::patch('/missed-requests/{missedAttendanceRequestId}', [MissedAttendanceRequestController::class, 'update'])->name('missed-requests.update');
        Route::get('/leave-requests', [LeaveRequestController::class, 'index'])->name('leave-requests.index');
        Route::get('/leave-requests/{leave}', [LeaveRequestController::class, 'show'])->name('leave-requests.show');
        Route::patch('/leave-requests/{leave}', [LeaveRequestController::class, 'update'])->name('leave-requests.update');
        Route::get('/labour-master', [LabourAttendanceController::class, 'master'])->name('labour-master.index');
        Route::get('/labour-attendance', [LabourAttendanceController::class, 'index'])->name('labour-attendance.index');
        Route::get('/labour-sites', [LabourAttendanceController::class, 'sites'])->name('labour-sites.index');
        Route::post('/labour-sites', [LabourAttendanceController::class, 'storeSite'])->name('labour-sites.store');
        Route::get('/labour-sites/{labourSite}/edit', [LabourAttendanceController::class, 'editSite'])->name('labour-sites.edit');
        Route::put('/labour-sites/{labourSite}', [LabourAttendanceController::class, 'updateSite'])->name('labour-sites.update');
        Route::delete('/labour-sites/{labourSite}', [LabourAttendanceController::class, 'destroySite'])->name('labour-sites.destroy');
        Route::get('/contractors', [LabourAttendanceController::class, 'contractors'])->name('contractors.index');
        Route::post('/contractors', [LabourAttendanceController::class, 'storeContractor'])->name('contractors.store');
        Route::get('/contractors/{contractor}/edit', [LabourAttendanceController::class, 'editContractor'])->name('contractors.edit');
        Route::put('/contractors/{contractor}', [LabourAttendanceController::class, 'updateContractor'])->name('contractors.update');
        Route::delete('/contractors/{contractor}', [LabourAttendanceController::class, 'destroyContractor'])->name('contractors.destroy');
        Route::get('/labours', [LabourAttendanceController::class, 'labours'])->name('labours.index');
        Route::post('/labours', [LabourAttendanceController::class, 'storeLabour'])->name('labours.store');
        Route::get('/labours/{labour}/edit', [LabourAttendanceController::class, 'editLabour'])->name('labours.edit');
        Route::put('/labours/{labour}', [LabourAttendanceController::class, 'updateLabour'])->name('labours.update');
        Route::delete('/labours/{labour}', [LabourAttendanceController::class, 'destroyLabour'])->name('labours.destroy');
        Route::get('/labour-attendance/{labourAttendance}/photo', [LabourAttendanceController::class, 'photo'])->name('labour-attendance.photo');
        Route::patch('/labour-attendance/{labourAttendance}', [LabourAttendanceController::class, 'update'])->name('labour-attendance.update');
        Route::get('/vehicle-drivers', [VehicleDriverAttendanceController::class, 'drivers'])->name('vehicle-drivers.index');
        Route::post('/vehicle-drivers', [VehicleDriverAttendanceController::class, 'storeDriver'])->name('vehicle-drivers.store');
        Route::get('/driver-attendance', [VehicleDriverAttendanceController::class, 'index'])->name('driver-attendance.index');
        Route::post('/driver-attendance', [VehicleDriverAttendanceController::class, 'store'])->name('driver-attendance.store');
        Route::get('/driver-attendance/export', [VehicleDriverAttendanceController::class, 'export'])->name('driver-attendance.export');
        Route::get('/driver-attendance/{vehicleDriverAttendance}/edit', [VehicleDriverAttendanceController::class, 'edit'])->name('driver-attendance.edit');
        Route::put('/driver-attendance/{vehicleDriverAttendance}', [VehicleDriverAttendanceController::class, 'update'])->name('driver-attendance.update');
        Route::get('/payments', [PaymentController::class, 'index'])->name('payments.index');
        Route::post('/payments/generate', [PaymentController::class, 'generate'])->name('payments.generate');
        Route::get('/payments/{payment}/slip', [PaymentController::class, 'slip'])->name('payments.slip');
        Route::get('/diesel-purchases', [DailyDieselPurchaseController::class, 'index'])->name('diesel-purchases.index');
        Route::post('/diesel-purchases/monthly-entries', [DailyDieselPurchaseController::class, 'storeMonthly'])->name('diesel-purchases.monthly');
        Route::get('/machinery-diesel-logs', [MachineryDieselLogController::class, 'index'])->name('machinery-diesel-logs.index');
        Route::post('/machinery-diesel-logs', [MachineryDieselLogController::class, 'store'])->name('machinery-diesel-logs.store');
        Route::get('/product-purchases', [ProductPurchaseController::class, 'index'])->name('product-purchases.index');
        Route::post('/product-purchases', [ProductPurchaseController::class, 'store'])->name('product-purchases.store');
        Route::put('/product-purchases/{productPurchase}', [ProductPurchaseController::class, 'update'])->name('product-purchases.update');
        Route::delete('/product-purchases/{productPurchase}', [ProductPurchaseController::class, 'destroy'])->name('product-purchases.destroy');
        Route::get('/materials', [MaterialStockController::class, 'materials'])->name('materials.index');
        Route::post('/materials', [MaterialStockController::class, 'storeMaterial'])->name('materials.store');
        Route::put('/materials/{material}', [MaterialStockController::class, 'updateMaterial'])->name('materials.update');
        Route::get('/material-stock', [MaterialStockController::class, 'stock'])->name('material-stock.index');
        Route::post('/material-stock/adjust', [MaterialStockController::class, 'adjustStock'])->name('material-stock.adjust');
        Route::get('/material-requests', [MaterialStockController::class, 'requests'])->name('material-requests.index');
        Route::patch('/material-requests/{materialRequestId}', [MaterialStockController::class, 'updateRequest'])->name('material-requests.update');
        Route::post('/material-requests/{materialRequestId}/issue', [MaterialStockController::class, 'issue'])->name('material-requests.issue');
        Route::get('/material-issues', [MaterialStockController::class, 'issues'])->name('material-issues.index');
        Route::get('/vehicles', [VehicleController::class, 'index'])->name('vehicles.index');
        Route::get('/vehicles/create', [VehicleController::class, 'create'])->name('vehicles.create');
        Route::post('/vehicles', [VehicleController::class, 'store'])->name('vehicles.store');
        Route::get('/vehicles/{vehicle}', [VehicleController::class, 'show'])->name('vehicles.show');
        Route::get('/vehicles/{vehicle}/edit', [VehicleController::class, 'edit'])->name('vehicles.edit');
        Route::put('/vehicles/{vehicle}', [VehicleController::class, 'update'])->name('vehicles.update');
        Route::post('/vehicles/{vehicle}/monthly-entries', [VehicleLogController::class, 'storeMonthly'])->name('vehicles.logs.monthly');
        Route::post('/vehicles/{vehicle}/logs', [VehicleLogController::class, 'store'])->name('vehicles.logs.store');
        Route::get('/vehicles/{vehicle}/logs/{vehicleLog}/edit', [VehicleLogController::class, 'edit'])->name('vehicles.logs.edit');
        Route::put('/vehicles/{vehicle}/logs/{vehicleLog}', [VehicleLogController::class, 'update'])->name('vehicles.logs.update');
        Route::get('/employees', [EmployeeController::class, 'index'])->name('employees.index');
        Route::get('/employees/create', [EmployeeController::class, 'create'])->name('employees.create');
        Route::post('/employees', [EmployeeController::class, 'store'])->name('employees.store');
        Route::post('/employees/{employee}/send-credentials', [EmployeeController::class, 'sendCredentials'])->name('employees.send-credentials');
        Route::get('/employees/{employee}/edit', [EmployeeController::class, 'edit'])->name('employees.edit');
        Route::put('/employees/{employee}', [EmployeeController::class, 'update'])->name('employees.update');
        Route::get('/employees/{employee}', [EmployeeController::class, 'show'])->name('employees.show');
    });
});
