<?php

return [
    'email' => env('ADMIN_EMAIL', 'constructkaroadmin@gmail.com'),
    'password' => env('ADMIN_PASSWORD', 'constructkaroadmin123456'),
    'permissions' => env('ADMIN_PERMISSIONS', '*'),
    'super_admin_permissions' => [
        'dashboard',
        'companies',
    ],
    'company_admin_permissions' => [
        'dashboard',
        'employees',
        'attendance_reports',
        'missed_requests',
        'leave_requests',
        'labour_attendance',
        'site_master',
        'contractor_master',
        'labour_master',
        'payments',
        'dpr_reports',
        'challans',
        'complaints',
        'fdd_test_records',
        'mir_file_reports',
        'vehicles',
        'diesel_purchases',
        'product_purchases',
    ],
    'module_permissions' => [
        'dashboard' => 'Dashboard',
        'hr' => 'HR Access',
        'purchase' => 'Purchase Access',
        'employees' => 'Employees',
        'attendance_reports' => 'Attendance Reports',
        'missed_requests' => 'Missed Requests',
        'leave_requests' => 'Leave Requests',
        'labour_attendance' => 'Labour Attendance',
        'site_master' => 'Site Master',
        'contractor_master' => 'Contractor Master',
        'labour_master' => 'Labour Master',
        'payments' => 'Payments',
        'dpr_reports' => 'DPR Reports',
        'challans' => 'Challans',
        'complaints' => 'Complaints',
        'fdd_test_records' => 'FDD Test Records',
        'mir_file_reports' => 'MIR File Reports',
        'vehicles' => 'Vehicles',
        'diesel_purchases' => 'Diesel Purchase',
        'product_purchases' => 'Product Purchase',
    ],
    'multi_device_login_mobiles' => [
        '9309886247',
    ],

    'navigation' => [
        [
            'label' => 'ConstructKaro',
            'items' => [
                [
                    'key' => 'companies',
                    'label' => 'Companies',
                    'route' => 'admin.companies.index',
                    'active' => 'admin.companies.*',
                ],
            ],
        ],
        [
            'label' => 'Overview',
            'items' => [
                [
                    'key' => 'dashboard',
                    'label' => 'Dashboard',
                    'route' => 'admin.dashboard',
                    'active' => 'admin.dashboard',
                ],
            ],
        ],
        [
            'label' => 'HR',
            'items' => [
                [
                    'key' => 'employees',
                    'label' => 'Employees',
                    'route' => 'admin.employees.index',
                    'active' => 'admin.employees.*',
                ],
                [
                    'key' => 'attendance_reports',
                    'label' => 'Attendance Reports',
                    'route' => 'admin.attendance-reports.index',
                    'active' => 'admin.attendance-reports.*',
                ],
                [
                    'key' => 'attendance_reports',
                    'label' => 'Today Attendance',
                    'route' => 'admin.today-attendance.index',
                    'active' => 'admin.today-attendance.*',
                ],
                [
                    'key' => 'missed_requests',
                    'label' => 'Missed Requests',
                    'route' => 'admin.missed-requests.index',
                    'active' => 'admin.missed-requests.*',
                ],
                [
                    'key' => 'leave_requests',
                    'label' => 'Leave Requests',
                    'route' => 'admin.leave-requests.index',
                    'active' => 'admin.leave-requests.*',
                ],
                [
                    'key' => 'labour_attendance',
                    'label' => 'Labour Attendance',
                    'route' => 'admin.labour-attendance.index',
                    'active' => 'admin.labour-attendance.*',
                ],
                [
                    'key' => 'payments',
                    'label' => 'Payments',
                    'route' => 'admin.payments.index',
                    'active' => 'admin.payments.*',
                ],
            ],
        ],
        [
            'label' => 'Purchase',
            'items' => [
                [
                    'key' => 'challans',
                    'label' => 'Challans',
                    'route' => 'admin.challans.index',
                    'active' => 'admin.challans.*',
                ],
                [
                    'key' => 'diesel_purchases',
                    'label' => 'Diesel Purchase',
                    'route' => 'admin.diesel-purchases.index',
                    'active' => 'admin.diesel-purchases.*',
                ],
                [
                    'key' => 'product_purchases',
                    'label' => 'Product Purchase',
                    'route' => 'admin.product-purchases.index',
                    'active' => 'admin.product-purchases.*',
                ],
            ],
        ],
        [
            'label' => 'Masters',
            'items' => [
                [
                    'key' => 'site_master',
                    'label' => 'Site Master',
                    'route' => 'admin.labour-sites.index',
                    'active' => 'admin.labour-sites.*',
                ],
                [
                    'key' => 'contractor_master',
                    'label' => 'Contractor Master',
                    'route' => 'admin.contractors.index',
                    'active' => 'admin.contractors.*',
                ],
                [
                    'key' => 'labour_master',
                    'label' => 'Labour Master',
                    'route' => 'admin.labours.index',
                    'active' => 'admin.labours.*',
                ],
            ],
        ],
        [
            'label' => 'Site Work',
            'items' => [
                [
                    'key' => 'dpr_reports',
                    'label' => 'DPR Reports',
                    'route' => 'admin.dpr-reports.index',
                    'active' => 'admin.dpr-reports.*',
                ],
                [
                    'key' => 'challans',
                    'label' => 'Challans',
                    'route' => 'admin.challans.index',
                    'active' => 'admin.challans.*',
                ],
                [
                    'key' => 'complaints',
                    'label' => 'Complaints',
                    'route' => 'admin.complaints.index',
                    'active' => 'admin.complaints.*',
                ],
            ],
        ],
        [
            'label' => 'Quality',
            'items' => [
                [
                    'key' => 'fdd_test_records',
                    'label' => 'FDD Test Records',
                    'route' => 'admin.fdd-test-records.index',
                    'active' => 'admin.fdd-test-records.*',
                ],
                [
                    'key' => 'mir_file_reports',
                    'label' => 'MIR File Reports',
                    'route' => 'admin.mir-file-reports.index',
                    'active' => 'admin.mir-file-reports.*',
                ],
            ],
        ],
        [
            'label' => 'Fleet',
            'items' => [
                [
                    'key' => 'vehicles',
                    'label' => 'Vehicles',
                    'route' => 'admin.vehicles.index',
                    'active' => 'admin.vehicles.*',
                ],
                [
                    'key' => 'diesel_purchases',
                    'label' => 'Diesel Purchase',
                    'route' => 'admin.diesel-purchases.index',
                    'active' => 'admin.diesel-purchases.*',
                ],
            ],
        ],
    ],

    'route_permissions' => [
        'admin.dashboard' => 'dashboard',
        'admin.companies.*' => 'companies',
        'admin.today-attendance.*' => 'attendance_reports',
        'admin.attendance-reports.*' => 'attendance_reports',
        'admin.missed-requests.*' => 'missed_requests',
        'admin.leave-requests.*' => 'leave_requests',
        'admin.labour-master.*' => 'labour_attendance',
        'admin.labour-attendance.*' => 'labour_attendance',
        'admin.labour-sites.*' => 'site_master',
        'admin.contractors.*' => 'contractor_master',
        'admin.labours.*' => 'labour_master',
        'admin.dpr-reports.*' => 'dpr_reports',
        'admin.fdd-test-records.*' => 'fdd_test_records',
        'admin.fdd-road-sections.*' => 'fdd_test_records',
        'admin.mir-file-reports.*' => 'mir_file_reports',
        'admin.challans.*' => 'challans',
        'admin.complaints.*' => 'complaints',
        'admin.payments.*' => 'payments',
        'admin.diesel-purchases.*' => 'diesel_purchases',
        'admin.product-purchases.*' => 'product_purchases',
        'admin.vehicles.*' => 'vehicles',
        'admin.employees.*' => 'employees',
    ],
];
