<?php

return [
    'email' => env('ADMIN_EMAIL', 'constructkaroadmin@gmail.com'),
    'password' => env('ADMIN_PASSWORD', 'constructkaroadmin123456'),
    'permissions' => env('ADMIN_PERMISSIONS', '*'),
    'super_admin_permissions' => [
        'dashboard',
        'companies',
    ],
    'company_admin_permissions' => [
        'dashboard',
        'employees',
        'attendance_reports',
        'missed_requests',
        'leave_requests',
        'labour_attendance',
        'labour_costing',
        'driver_attendance',
        'site_master',
        'contractor_master',
        'labour_master',
        'supplier_master',
        'unit_master',
        'payments',
        'dpr_reports',
        'challans',
        'complaints',
        'fdd_test_records',
        'mir_file_reports',
        'vehicles',
        'vehicle_maintenance',
        'diesel_purchases',
        'machinery_diesel_logs',
        'product_purchases',
        'purchase_workflows',
        'purchase_orders',
        'material_stock',
        'project_management',
        'site_reports',
        'erp_gap_analysis',
    ],
    'module_permissions' => [
        'dashboard' => 'Dashboard',
        'hr' => 'HR Access',
        'engg' => 'Engg Access',
        'purchase' => 'Purchase Access',
        'project_management' => 'Project Management',
        'site_reports' => 'Site Reports',
        'erp_gap_analysis' => 'ERP Gap Analysis',
        'employees' => 'Employees',
        'attendance_reports' => 'Attendance Reports',
        'missed_requests' => 'Missed Requests',
        'leave_requests' => 'Leave Requests',
        'labour_attendance' => 'Labour Attendance',
        'labour_costing' => 'Labour Costing',
        'driver_attendance' => 'Driver Attendance',
        'site_master' => 'Site Master',
        'contractor_master' => 'Contractor Master',
        'labour_master' => 'Labour Master',
        'supplier_master' => 'Supplier Master',
        'unit_master' => 'Unit Master',
        'payments' => 'Payments',
        'dpr_reports' => 'DPR Reports',
        'challans' => 'Challans',
        'complaints' => 'Complaints',
        'fdd_test_records' => 'FDD Test Records',
        'mir_file_reports' => 'MIR File Reports',
        'vehicles' => 'Vehicles',
        'vehicle_maintenance' => 'Fleet Maintenance',
        'diesel_purchases' => 'Diesel Purchase',
        'machinery_diesel_logs' => 'Machinery Diesel',
        'product_purchases' => 'Product Purchase',
        'purchase_workflows' => 'Purchase Workflow',
        'purchase_orders' => 'Purchase Orders',
        'material_stock' => 'Store & Inventory',
    ],
    'multi_device_login_mobiles' => [
        '9309886247',
    ],

    'paid_holidays' => [
        2026 => [
            '2026-01-26' => 'Republic Day',
            '2026-02-19' => 'Chhatrapati Shivaji Maharaj Jayanti',
            '2026-03-03' => 'Holi',
            '2026-03-19' => 'Gudhipadwa',
            '2026-05-01' => 'Maharashtra Day',
            '2026-08-15' => 'Independence Day',
            '2026-09-05' => 'Gokul Ashtami',
            '2026-09-14' => 'Ganesh Chaturthi',
            '2026-09-19' => 'Gauri Visarjan',
            '2026-10-20' => 'Vijayadashami/Dasra',
            '2026-11-08' => 'Laxmipujan',
            '2026-11-11' => 'Bhaubeej',
        ],
    ],

    'navigation' => [
        [
            'label' => 'ConstructKaro',
            'items' => [
                [
                    'key' => 'companies',
                    'label' => 'Companies',
                    'route' => 'admin.companies.index',
                    'active' => 'admin.companies.*',
                ],
            ],
        ],
        [
            'label' => 'Overview',
            'items' => [
                [
                    'key' => 'dashboard',
                    'label' => 'Dashboard',
                    'route' => 'admin.dashboard',
                    'active' => 'admin.dashboard',
                ],
                [
                    'key' => 'erp_gap_analysis',
                    'label' => 'ERP Gap Analysis',
                    'route' => 'admin.erp-gap-analysis.index',
                    'active' => 'admin.erp-gap-analysis.*',
                ],
            ],
        ],
        [
            'label' => 'Projects',
            'items' => [
                [
                    'key' => 'project_management',
                    'label' => 'Project Management',
                    'route' => 'admin.projects.index',
                    'active' => 'admin.projects.*',
                ],
            ],
        ],
        [
            'label' => 'HR',
            'items' => [
                [
                    'key' => 'employees',
                    'label' => 'Employees',
                    'route' => 'admin.employees.index',
                    'active' => 'admin.employees.*',
                ],
                [
                    'key' => 'attendance_reports',
                    'label' => 'Attendance Reports',
                    'route' => 'admin.attendance-reports.index',
                    'active' => 'admin.attendance-reports.*',
                ],
                [
                    'key' => 'attendance_reports',
                    'label' => 'Today Attendance',
                    'route' => 'admin.today-attendance.index',
                    'active' => 'admin.today-attendance.*',
                ],
                [
                    'key' => 'missed_requests',
                    'label' => 'Missed Requests',
                    'route' => 'admin.missed-requests.index',
                    'active' => 'admin.missed-requests.*',
                ],
                [
                    'key' => 'leave_requests',
                    'label' => 'Leave Requests',
                    'route' => 'admin.leave-requests.index',
                    'active' => 'admin.leave-requests.*',
                ],
                [
                    'key' => 'labour_attendance',
                    'label' => 'Labour Attendance',
                    'route' => 'admin.labour-attendance.index',
                    'active' => 'admin.labour-attendance.*',
                ],
                [
                    'key' => 'labour_costing',
                    'label' => 'Labour Costing',
                    'route' => 'admin.labour-costing.index',
                    'active' => 'admin.labour-costing.*',
                ],
                [
                    'key' => 'driver_attendance',
                    'label' => 'Vehicle Drivers',
                    'route' => 'admin.vehicle-drivers.index',
                    'active' => 'admin.vehicle-drivers.*',
                ],
                [
                    'key' => 'driver_attendance',
                    'label' => 'Driver Attendance',
                    'route' => 'admin.driver-attendance.index',
                    'active' => 'admin.driver-attendance.*',
                ],
                [
                    'key' => 'payments',
                    'label' => 'Payments',
                    'route' => 'admin.payments.index',
                    'active' => 'admin.payments.*',
                ],
            ],
        ],
        [
            'label' => 'Purchase Management',
            'items' => [
                [
                    'key' => 'purchase_orders',
                    'label' => 'Purchase Orders',
                    'route' => 'admin.purchase-orders.index',
                    'active' => 'admin.purchase-orders.*',
                ],
                [
                    'key' => 'challans',
                    'label' => 'Challans',
                    'route' => 'admin.challans.index',
                    'active' => 'admin.challans.*',
                ],
                [
                    'key' => 'diesel_purchases',
                    'label' => 'Diesel Purchase',
                    'route' => 'admin.diesel-purchases.index',
                    'active' => 'admin.diesel-purchases.*',
                ],
                [
                    'key' => 'product_purchases',
                    'label' => 'Product Purchase',
                    'route' => 'admin.product-purchases.index',
                    'active' => 'admin.product-purchases.*',
                ],
            ],
        ],
        [
            'label' => 'Store & Inventory',
            'items' => [
                [
                    'key' => 'material_stock',
                    'label' => 'Material Master',
                    'route' => 'admin.materials.index',
                    'active' => 'admin.materials.*',
                ],
                [
                    'key' => 'material_stock',
                    'label' => 'Stock List',
                    'route' => 'admin.material-stock.index',
                    'active' => 'admin.material-stock.*',
                ],
                [
                    'key' => 'material_stock',
                    'label' => 'Material Requests',
                    'route' => 'admin.material-requests.index',
                    'active' => 'admin.material-requests.*',
                ],
                [
                    'key' => 'material_stock',
                    'label' => 'Material Issues',
                    'route' => 'admin.material-issues.index',
                    'active' => 'admin.material-issues.*',
                ],
                [
                    'key' => 'material_stock',
                    'label' => 'Safety Store',
                    'route' => 'admin.safety-store.index',
                    'active' => 'admin.safety-store.*',
                ],
            ],
        ],
        [
            'label' => 'Masters',
            'items' => [
                [
                    'key' => 'site_master',
                    'label' => 'Site Master',
                    'route' => 'admin.labour-sites.index',
                    'active' => 'admin.labour-sites.*',
                ],
                [
                    'key' => 'contractor_master',
                    'label' => 'Contractor Master',
                    'route' => 'admin.contractors.index',
                    'active' => 'admin.contractors.*',
                ],
                [
                    'key' => 'labour_master',
                    'label' => 'Labour Master',
                    'route' => 'admin.labours.index',
                    'active' => 'admin.labours.*',
                ],
                [
                    'key' => 'supplier_master',
                    'label' => 'Supplier Master',
                    'route' => 'admin.suppliers.index',
                    'active' => 'admin.suppliers.*',
                ],
                [
                    'key' => 'unit_master',
                    'label' => 'Unit Master',
                    'route' => 'admin.units.index',
                    'active' => 'admin.units.*',
                ],
            ],
        ],
        [
            'label' => 'Site Work',
            'items' => [
                [
                    'key' => 'dpr_reports',
                    'label' => 'DPR Reports',
                    'route' => 'admin.dpr-reports.index',
                    'active' => 'admin.dpr-reports.*',
                ],
                [
                    'key' => 'site_reports',
                    'label' => 'Site Reports',
                    'route' => 'admin.site-reports.index',
                    'active' => 'admin.site-reports.*',
                ],
                [
                    'key' => 'challans',
                    'label' => 'Challans',
                    'route' => 'admin.challans.index',
                    'active' => 'admin.challans.*',
                ],
                [
                    'key' => 'complaints',
                    'label' => 'Complaints',
                    'route' => 'admin.complaints.index',
                    'active' => 'admin.complaints.*',
                ],
            ],
        ],
        [
            'label' => 'Quality',
            'items' => [
                [
                    'key' => 'fdd_test_records',
                    'label' => 'FDD Test Records',
                    'route' => 'admin.fdd-test-records.index',
                    'active' => 'admin.fdd-test-records.*',
                ],
                [
                    'key' => 'mir_file_reports',
                    'label' => 'MIR File Reports',
                    'route' => 'admin.mir-file-reports.index',
                    'active' => 'admin.mir-file-reports.*',
                ],
            ],
        ],
        [
            'label' => 'Fleet',
            'items' => [
                [
                    'key' => 'vehicles',
                    'label' => 'Vehicles',
                    'route' => 'admin.vehicles.index',
                    'active' => 'admin.vehicles.*',
                ],
                [
                    'key' => 'vehicle_maintenance',
                    'label' => 'Fleet Maintenance',
                    'route' => 'admin.vehicle-maintenance.index',
                    'active' => 'admin.vehicle-maintenance.*',
                ],
                [
                    'key' => 'machinery_diesel_logs',
                    'label' => 'Machinery Diesel',
                    'route' => 'admin.machinery-diesel-logs.index',
                    'active' => 'admin.machinery-diesel-logs.*',
                ],
            ],
        ],
    ],

    'route_permissions' => [
        'admin.dashboard' => 'dashboard',
        'admin.erp-gap-analysis.*' => 'erp_gap_analysis',
        'admin.companies.*' => 'companies',
        'admin.today-attendance.*' => 'attendance_reports',
        'admin.attendance-reports.*' => 'attendance_reports',
        'admin.missed-requests.*' => 'missed_requests',
        'admin.leave-requests.*' => 'leave_requests',
        'admin.labour-master.*' => 'labour_attendance',
        'admin.labour-attendance.*' => 'labour_attendance',
        'admin.labour-costing.*' => 'labour_costing',
        'admin.vehicle-drivers.*' => 'driver_attendance',
        'admin.driver-attendance.*' => 'driver_attendance',
        'admin.labour-sites.*' => 'site_master',
        'admin.contractors.*' => 'contractor_master',
        'admin.labours.*' => 'labour_master',
        'admin.dpr-reports.*' => 'dpr_reports',
        'admin.fdd-test-records.*' => 'fdd_test_records',
        'admin.fdd-road-sections.*' => 'fdd_test_records',
        'admin.mir-file-reports.*' => 'mir_file_reports',
        'admin.challans.*' => 'challans',
        'admin.complaints.*' => 'complaints',
        'admin.payments.*' => 'payments',
        'admin.diesel-purchases.*' => 'diesel_purchases',
        'admin.machinery-diesel-logs.*' => 'machinery_diesel_logs',
        'admin.purchase-workflows.*' => 'purchase_workflows',
        'admin.purchase-orders.*' => 'purchase_orders',
        'admin.product-purchases.*' => 'product_purchases',
        'admin.projects.*' => 'project_management',
        'admin.site-reports.*' => 'site_reports',
        'admin.materials.*' => 'material_stock',
        'admin.material-stock.*' => 'material_stock',
        'admin.material-requests.*' => 'material_stock',
        'admin.material-issues.*' => 'material_stock',
        'admin.safety-store.*' => 'material_stock',
        'admin.suppliers.*' => 'supplier_master',
        'admin.units.*' => 'unit_master',
        'admin.vehicle-maintenance.*' => 'vehicle_maintenance',
        'admin.vehicles.*' => 'vehicles',
        'admin.employees.*' => 'employees',
    ],
];
